import type { Store } from '../storage/store';

export const FOLDERS_PATH = 'wiki/folders.json';
export const INBOX_PATH = 'inbox';

export interface Folder {
  path: string;        // slash-separated, lowercase-hyphenated
  name: string;        // human display name (any unicode)
  created_at: string;  // ISO
  /** Tree parent. `null`/undefined = root, `"folder:<path>"` = subfolder. Folders cannot be under notes. */
  parent?: string | null;
  /** Fractional-indexed sibling order. Generated by tree/order.ts. */
  order?: string;
}

const VALID_PATH = /^[a-z0-9-]+(\/[a-z0-9-]+)*$/;

export function isValidFolderPath(path: string): boolean {
  return typeof path === 'string' && path.length > 0 && VALID_PATH.test(path);
}

export async function loadFolders(store: Store): Promise<Folder[]> {
  try {
    return await store.readJSON<Folder[]>(FOLDERS_PATH);
  } catch {
    return [];
  }
}

export async function saveFolders(store: Store, folders: Folder[]): Promise<void> {
  await store.writeJSON(FOLDERS_PATH, folders);
}

/**
 * Idempotent: ensure the Inbox folder exists. Creates folders.json if missing.
 * Inbox is the fallback bucket for unclassified or classification-failed notes.
 */
export async function ensureInbox(store: Store): Promise<void> {
  const existing = await loadFolders(store);
  if (existing.some((f) => f.path === INBOX_PATH)) return;
  existing.unshift({
    path: INBOX_PATH,
    name: 'Inbox',
    created_at: new Date().toISOString(),
    parent: null,
    order: 'a0',
  });
  await saveFolders(store, existing);
}
