// apps/mcp/src/tools/rebuild-index.ts
import { z } from 'zod';
import { join } from 'node:path';
import { readdir, stat, writeFile, readFile } from 'node:fs/promises';
import type { Context } from '../context.js';
import { textResult, errorResult } from '../lib/error.js';
import { resolveProjectId } from '../lib/resolve-project.js';
import { projectPaths } from '@mindbase/core';

export const inputSchema = z.object({
  projectId: z.string().optional(),
});

export const definition = {
  name: 'mindbase_rebuild_index',
  description: 'Regenerate index.yaml by scanning the project tree. Always overwrites; never partial-merges. Output schema: { project, files, contributors, sources, last_build }.',
  inputSchema: {
    type: 'object',
    properties: { projectId: { type: 'string', description: 'Project id; defaults to the current project (config.json)' } },
      },
};

async function walkRel(root: string, sub: string): Promise<string[]> {
  const dir = join(root, sub);
  const out: string[] = [];
  let entries: string[] = [];
  try { entries = await readdir(dir); } catch { return out; }
  for (const e of entries) {
    const full = join(dir, e);
    const rel = sub ? `${sub}/${e}` : e;
    try {
      const s = await stat(full);
      if (s.isDirectory()) out.push(...(await walkRel(root, rel)));
      else if (e.endsWith('.md')) out.push(rel);
    } catch { /* skip */ }
  }
  return out;
}

export async function handle(ctx: Context, rawInput: unknown) {
  const parsed = inputSchema.safeParse(rawInput);
  if (!parsed.success) return errorResult(`Invalid input: ${parsed.error.issues[0]?.message}`);
  const resolved = await resolveProjectId(ctx, parsed.data.projectId);
  if (!resolved.ok) return errorResult(resolved.error);
  const projectId = resolved.projectId;
  const root = join(ctx.dataDir, 'projects', projectId);
  const p = projectPaths();

  let projectName = projectId;
  try {
    const readme = await readFile(join(root, p.readme), 'utf-8');
    const m = readme.match(/^#\s+([^\n]+?)(?:\s+—|$)/);
    if (m && m[1]) projectName = m[1].trim();
  } catch { /* ok */ }

  const contributors = await walkRel(root, p.contributorsRoot);
  const research = await walkRel(root, p.researchDir);
  let contextMtime = '';
  try { contextMtime = new Date((await stat(join(root, p.context))).mtimeMs).toISOString(); } catch { /* ok */ }

  const contributorsByUser = new Map<string, string[]>();
  for (const f of contributors) {
    const parts = f.split('/');
    const user = parts[2] ?? 'unknown';
    const day = parts[3] ?? '';
    if (!contributorsByUser.has(user)) contributorsByUser.set(user, []);
    contributorsByUser.get(user)!.push(day.replace('.md', ''));
  }

  const yaml = [
    `# Auto-generated by mindbase_rebuild_index — do not edit manually.`,
    `project:`,
    `  id: ${projectId}`,
    `  name: ${projectName}`,
    `  last_build: ${contextMtime}`,
    `files:`,
    `  context: ${p.context}`,
    `  readme: ${p.readme}`,
    `contributors:`,
    ...Array.from(contributorsByUser.entries()).flatMap(([u, days]) => [
      `  - name: ${u}`,
      `    last_contribution: ${days.sort().pop() ?? ''}`,
      `    entry_count: ${days.length}`,
    ]),
    `sources:`,
    `  research: ${research.length}`,
    `  contributor_entries: ${contributors.length}`,
    ``,
  ].join('\n');

  await writeFile(join(root, p.indexYaml), yaml, 'utf-8');
  return textResult({ projectId, indexYaml: p.indexYaml, contributors: contributors.length, research: research.length });
}

export function register(handlers: Map<string, (input: unknown) => Promise<unknown>>, defs: object[], ctx: Context): void {
  handlers.set(definition.name, (input) => handle(ctx, input));
  defs.push(definition);
}
