// Shared types for Atlas core. No framework imports.

export type EditState = 'auto' | 'human_touched';

export type Visibility = 'public' | 'internal' | 'pii';

export type WikiFileType = 'concept' | 'article' | 'source' | 'index';

/**
 * Note kind — UX differentiation only; storage is unified across all kinds.
 * Known values get literal-type autocomplete and exhaustiveness checking;
 * `(string & {})` keeps the union open for user-defined templates without
 * collapsing the named literals.
 */
export type NoteKind = 'concept' | 'note' | 'daily' | 'meeting' | 'person' | 'project' | (string & {});

export type ProviderName = 'openai' | 'anthropic' | 'deepseek' | 'ollama' | 'atlas';

/**
 * Capture surface — what device/channel introduced a source into the system.
 * Orthogonal to MetaJson.created_via (which records who wrote the wiki page itself).
 */
export type CaptureSurface = 'browser-ext' | 'ios' | 'android' | 'voice' | 'manual' | 'rss';

export interface MetaJson {
  id: string;
  type: WikiFileType;
  title: string;
  created: string; // ISO
  updated: string; // ISO
  sources: string[]; // raw ids or raw paths
  related: string[]; // other concept slugs
  one_liner: string;
  word_count: number;
  compile_version: number;
  edit_state: EditState;
  last_human_edit: string | null;
  visibility?: Visibility; // 'public' (default) | 'internal' | 'pii'
  project?: string; // optional project grouping (e.g. 'ml-research', 'work')
  created_via?: 'mcp' | 'web' | 'cli' | 'extension';
  mcp_client?: string;
  mcp_tool?: string;
  // Capture provenance — populated when a wiki page is compiled from a captured source.
  captured_via?: CaptureSurface;
  captured_url?: string;
  captured_device?: string;
  captured_at?: string; // ISO; mirror of raw doc's captured_at, set on compile from capture
  tags?: string[]; // free-form tags surfaced via WikiFileSummary.tags and frontmatter
  /** Logical folder path (e.g. "knowledge/machine-learning"). null = unfiled, renders in Inbox. */
  folder?: string | null;
  /** "llm" means the auto-classifier set this; "user" means the human did and the LLM must not overwrite. */
  folder_set_by?: 'llm' | 'user';
  /** ISO timestamp of last folder change. */
  folder_classified_at?: string;
  /** One-sentence LLM rationale, shown as tooltip on the breadcrumb. */
  folder_reason?: string;
  /** Tree parent. `null` = root, `"note:<slug>"` = under a note, `"folder:<path>"` = under a folder. */
  parent?: string | null;
  /** Fractional-indexed sibling order within the same parent. Generated by tree/order.ts. */
  order?: string;
  /**
   * Note kind — orthogonal to `type` (file-structure classification). `kind`
   * describes authorship intent and picks the UI template. Optional with
   * implicit default `'concept'` for backward compat — existing pages without
   * this field are treated as LLM-compiled concepts.
   */
  kind?: NoteKind;
}

export interface RawDoc {
  id: string;
  path: string; // e.g. raw/2026-04-08/a1b2c3
  title: string;
  source_url: string | null;
  captured_at: string; // ISO
  content: string;
  images: string[]; // relative paths
  // Capture provenance — present when the raw doc came from the universal capture pipeline.
  captured_via?: CaptureSurface;
  captured_device?: string;
  tags?: string[];
  /**
   * Relative path to the original binary file alongside content (.md). e.g.
   * 'raw/2026-05-22/abc123.pdf'. Present when the import preserved the binary
   * (Drive import for PDF/DOCX as of commit 01701ab). Adapters that
   * `supportsPDFs` use this to attach the binary to the LLM request instead
   * of the extracted text.
   */
  binary_path?: string;
  /** MIME type of binary_path, e.g. 'application/pdf'. */
  binary_mime?: string;
}

export interface RawMetaJson {
  id: string;
  title: string;
  source_url: string | null;
  captured_at: string;
  kind: 'paste' | 'upload-md' | 'upload-txt' | 'upload-pdf' | 'web-clip' | 'capture';
  captured_via?: CaptureSurface;
  captured_device?: string;
  tags?: string[];
  /** Logical folder path (e.g. "knowledge/papers"). null = unfiled, renders in Inbox. */
  folder?: string | null;
  /** Who set the folder. 'user' locks against future auto-classify. */
  folder_set_by?: 'llm' | 'user';
  /** ISO timestamp of last folder change. */
  folder_classified_at?: string;
  /** Human-readable reason from the classifier. */
  folder_reason?: string;
  /** Optional binary sidecar (set by ingest for PDFs etc.). */
  binary_path?: string;
  binary_mime?: string;
}

// LLM adapter types
export type ContentBlock =
  | { type: 'text'; text: string }
  | { type: 'document'; media_type: 'application/pdf'; data: string }  // base64
  | { type: 'image'; media_type: 'image/png' | 'image/jpeg' | 'image/gif' | 'image/webp'; data: string };

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  /**
   * Message content. A plain string is the common case (text-only). An array
   * of ContentBlock allows multimodal input: a text instruction followed by
   * a PDF document block, or text + image. Adapters that don't support a
   * given block type should throw at chat() time, not silently drop.
   */
  content: string | ContentBlock[];
  name?: string;
  tool_call_id?: string;
  /**
   * Tool calls emitted by the assistant in this turn. Required on assistant
   * messages when the model chose to call tools — must be present before any
   * subsequent `tool` role messages that carry results.
   */
  tool_calls?: ToolCall[];
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>; // JSON Schema
}

export interface ToolCall {
  id: string;
  name: string;
  arguments: Record<string, unknown>;
}

export interface ChatRequest {
  model: string;
  messages: ChatMessage[];
  tools?: ToolDefinition[];
  max_tokens?: number;
  temperature?: number;
}

export type ChatChunk =
  | { kind: 'delta'; text: string }
  /** Hidden-reasoning tokens from thinking models — progress signal, not answer text. */
  | { kind: 'thinking'; text: string }
  | { kind: 'tool_call'; tool_call: ToolCall }
  | { kind: 'done'; usage: { input_tokens: number; output_tokens: number } }
  | { kind: 'error'; error: string };

// Wiki listing
export interface WikiFileSummary {
  path: string;
  slug: string;
  title: string;
  one_liner: string;
  type: WikiFileType;
  edit_state: EditState;
  updated: string;          // ISO timestamp from meta.updated
  tags?: string[];          // first 3 tags from meta.tags
  incoming_count?: number;  // populated by graph routes only
  kind?: string;            // optional note kind (from MetaJson.kind)
  folder?: string | null;   // logical folder path; null = unfiled (Inbox)
  /** Tree parent (mirrors MetaJson.parent) — projected by /api/wiki listing. */
  parent?: string | null;
  /** Fractional-indexed sibling order (mirrors MetaJson.order). */
  order?: string;
}
